# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfNuubpa3-Ne6txAY45atZCNWf_0QECt
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/supermarket_sales.csv")

invoice = df["Invoice ID"].to_numpy()
print(invoice)

branch = df["Branch"].to_numpy()
print(branch)

city = df["City"].to_numpy()
print(city)

customer = df["Customer"].to_numpy()
print(customer)

gender = df["Gender"].to_numpy()
print(gender)

product = df["Product line"].to_numpy()
print(product)

unit = df["Unit price"].to_numpy()
print(unit)

quantity = df["Quantity"].to_numpy()
print(quantity)

tax = df["Tax 5%"].to_numpy()
print(tax)

total = df["Total"].to_numpy()
print(total)

date = df["Date"].to_numpy()
print(date)

time = df["Time"].to_numpy()
print(time)

payment = df["Payment"].to_numpy()
print(payment)

cogs = df["Cogs"].to_numpy()
print(cogs)

gross = df["gross mar"].to_numpy()
print(gross)

gross = df["gross income"].to_numpy()
print(gross)

rating = df["Rating"].to_numpy()
print(rating)



city = df["City"].to_numpy()
print(city[:5])

customer = df["Customer type"].to_numpy()
print(customer[:5])

gender = df["Gender"].to_numpy()
print(gender[:5])

product = df["Product line"].to_numpy()
print(product[:5])

unit = df["Unit price"].to_numpy()
print(unit[:5])

quantity = df["Quantity"].to_numpy()
print(quantity[:5])

tax = df["Tax 5%"].to_numpy()
print(tax[:5])

total = df["Total"].to_numpy()
print(total[:5])

date = df["Date"].to_numpy()
print(date[:5])

time = df["Time"].to_numpy()
print(time[:5])

payment = df["Payment"].to_numpy()
print(payment[:5])

cogs = df["Cogs"].to_numpy()
print(cogs[:5])

gross_margin_percentage = df["gross margin percentage"].to_numpy()
print(gross_margin_percentage[:5])

gross_income = df["gross income"].to_numpy()
print(gross_income[:5])

rating = df["Rating"].to_numpy()
print(rating[:5])

total_sales = np.sum(total)
print(f"Total Sales: {total_sales:.2f}")
average_sales = np.mean(total)
print(f"Average Sales: {average_sales:.2f}")

first_ten_sales = total[:10]
print(f"First 10 sales records: {first_ten_sales}")



mean_sales = np.mean(total)
print(f"Mean Sales: {mean_sales:.2f}")

median_sales = np.median(total)
print(f"Median Sales: {median_sales:.2f}")

variance_sales = np.var(total)
print(f"Variance of Sales: {variance_sales:.2f}")

std_dev_sales = np.std(total)
print(f"Standard Deviation of Sales: {std_dev_sales:.2f}")

"""The previous calculations such as `total_sales`, `average_sales`, `mean_sales`, `median_sales`, `variance_sales`, `std_dev_sales`, and `revenue` already utilized vectorized computations. NumPy operations are designed to be vectorized, which makes them very efficient for data analysis.

Let's consider another example: calculating the total sales before tax. We know that `total = unit * quantity + tax`, so `taxable_sales = total - tax`.
"""

taxable_sales = total - tax
print(f"First 5 taxable sales values: {taxable_sales[:5]}")
print(f"Total Taxable Sales: {np.sum(taxable_sales):.2f}")

revenue = unit * quantity
print(f"First 5 revenue values: {revenue[:5]}")